name:                vislack
version:             0.1.0.0
github:              "WhoMeNope/vislack"
license:             BSD3
author:              "Martin Toman"
maintainer:          "toman.martin@live.com"
copyright:           "Martin Toman"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/WhoMeNope/vislack#readme>

dependencies:
- base >= 4.7 && < 5
- slack-web >= 0.2.0 && < 0.2.1
- transformers >= 0.5.5 && < 0.6
- text == 1.2.*
- json == 0.10.*
- directory == 1.3.1.5

library:
  source-dirs: src

executables:
  vislack-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vislack

tests:
  vislack-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vislack
